### ISSUE TITLE
Defaults not set on load

### ISSUE THREAD

**Issue by cthorner** [ckdake/setler#37]
Not sure if this is "working as designed". My scenario is:

I've created some unscoped settings:

Featureflags.all_settings is set to { "test": true }

however

Featureflags.defaults is still returns {}

so my scoped settings(e.g., myobject.featureflags.all_settings) become {} as well.

An easy fix is:

Featureflags.defaults = Featureflags.all_settings

Not exactly sure when to call this(can't put it in an initializer since it depends the database already existing). 

Now, myobject.featureflags.all_settings returns { "test": true }

I can see how the existing functionality would allow more flexible scenarios, but it is confusing enough that it might warrant a short explanation in the readme. Thoughts?

**Comment by ckdake** [comment]
Are you running on master or the most recent release?  Could you take a look in https://github.com/ckdake/setler/blob/master/test/settings_test.rb and see if you think we're missing a test and/or not covering this correctly?

**Comment by cthorner** [comment]
I'm on setler-0.0.13. I'll take a look at settings_test.rb

**Comment by cthorner** [comment]
I think maybe it should have been caught here:

https://github.com/ckdake/setler/blob/master/test/settings_test.rb#L127

but from what I can see Preferences doesn't have any settings so the assertion passes.

**Comment by ckdake** [comment]
(Sorry, I don't spend too much time on this gem any more and it's been a while)

From reading back, the intention of all_settings is to access things that have been set already and not to act as a modifier. If you are setting all_settings to something, this is not something currently supported or suggested in the README.  

Could you tell more about what you are trying to do? Is there a reason you do not want to set the defaults directly instead of first setting all_settings?

**Comment by cthorner** [comment]
Ok, sure. Thanks for keeping this project alive by addressing issues like this. Much appreciated.

I wasn't trying to say we should set all_settings to something, so let me just write out the code I had in mind:

```
Preferences.defaults # evaluates to {}
Preferences.all_settings # evaluates to {}
Preferences[:feature1] = true

Preferences.all_settings # evaluates to { feature1: true }
Preferences.defaults # still evaluates to {} !!! Is this the intention of the gem? 
                                  # Now, if we look at a scoped setting
u = User.new # User class has_setler :preferences

u.preferences.all_settings # this also evaluates to {}, not to {feature1: true}
```

Does that make sense? I'm not sure if this is how setler is supposed to work. My problem with this is that if I set some settings on Preferences they are not loaded into Preferences.defaults when I boot the application. Furthermore, I can't do this in the initializers or after_initializers, because I need access to the database which may not exist at that point(e.g, if called from a rake script). My current workaround is to override Preferences.defaults like this:

```
  def self.defaults()
      Hash[thing_scoped.all.collect{ |s| [s.var, s.value] }]
  end
```

Which works just fine for my purposes, but feels like a hack. When I first started using the gem I expected defaults, and by extension: user.preferences.all_settings which starts out with defaults and includes Preferences.where(thing_type: User, thing_type: user.id) as well,  to return anything where: Preferences.where(thing_type: nil, thing_id: nil). Which it doesn't - it just returns whatever happens to be stored in the defaults variable, regardless of what is stored in the database.

If this is "working as designed" it would be helpful with a note in the Readme to explain all of this.

**Comment by ckdake** [comment]
```Preferences.defaults``` should still evaluate to {} in your example, because you have not set any defaults yet. 

I think this is confusing because there are two different/separate ways that Setler is intended to be used:

1. Application level Feature Flags (e.g. new_ui_enabled for the entire application)
2. User level Feature Flags (e.g. new_ui_enabled for a particular user)

Mixing together Preferences's settings and a User's settings is not the intention.

**Comment by cthorner** [comment]
Ok, that makes sense. Having global settings stored in the database would be nice, but there are ways  around it. Your last comment may be worth including in the readme.

**Comment by ckdake** [comment]
Readme updated, marking this one as closed. Let me know if it could use more clarity.
