### ISSUE TITLE
test_multithreaded_create test in test/settings_test.rb is failing locally but not on TravisCI

### ISSUE THREAD

**Issue by jasnow** [ckdake/setler#40]
test_multithreaded_create test in test/settings_test.rb is failing
on my system (Ubuntu 14.04) but not on Travis. This is the error message:
```
SettingsTest#test_multithreaded_create [.../Projects/setler/test/settings_test.rb:83]:
[ActiveRecord::RecordNotUnique] exception expected, not
Class: <ActiveRecord::StatementInvalid>
Message: <"SQLite3::ConstraintException: UNIQUE constraint failed:
settings.var: INSERT INTO \"settings\" (\"created_at\", \"thing_id\",
\"thing_type\", \"updated_at\", \"value\", \"var\") VALUES (?, ?, ?, ?, ?, ?)">
---Backtrace---
```
Unclear how to fix it, but wanted to document it.
Running the same code as @ckdake's master

**Comment by jasnow** [comment]
Appears to be related to the recent commit: https://github.com/tsubery/setler/commit/32c8c6c7c0938f2636d64e8abfe79cad4c326650

**Comment by ckdake** [comment]
Definitely related to that commit. This may be one of those SQLite -vs- real db things.  @tsubery want to try figuring this one out?

**Comment by tsubery** [comment]
I think this test is just a false negative.
What version of activerecord are you using?

**Comment by jasnow** [comment]
My steps:
 * Run "git pull upstream master"
 * Run "appraisal install"
 * Run "appraisal rake test" and got above error.

>>  What version of activerecord are you using?

Here is the subcommand from "appraisal rake test" command to see the error:
 * BUNDLE_GEMFILE=/home/jasnow/Projects/setler/gemfiles/rails_3.gemfile bundle exec rake test

**Comment by tsubery** [comment]
Thanks. I fixed the test and this time ran the whole test matrix with appraisal.
Here's the pr https://github.com/ckdake/setler/pull/41

**Comment by jasnow** [comment]
#41 fixed it.
