### ISSUE TITLE
Rails 4/5 compatibility

### ISSUE THREAD

**Issue by Oshuma** [ckdake/setler#45]
We're upgrading an app from Rails 3.2 to 4.2 and running into issues with setler v0.0.13.  Are there any plans to update this library with Rails 4/5 compatibility, or is this project considered dead?

Ruby:
```ruby
user.preferences.testsetting = false
```

Postgres Error:
```
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "testsetting"
: SELECT  "preferences".* FROM "preferences" WHERE "preferences"."thing_type" = $1 AND "preferences"."thing_type" = $2 AND "preferences"."thing_id" = $3 AND "preferences"."thing_id" = $4 AND "preferences"."
var" = $5 LIMIT 1
```

**Comment by ckdake** [comment]
While not 'dead', I'm definitely not doing any further dev work on setler. Pull requests are welcomed and I'll happily review/merge/release, but I won't be figuring this one out on my own. Maybe @jasnow is looking for something to upgrade?

**Comment by jasnow** [comment]
My version is running Rails 5.1.0 and Ruby 2.3.4.
**rake** gets a lot of **warning: instance variable @object not initialized**.
I will be glad to create a PR and let you ( @ckdake ) review it.

**Comment by jasnow** [comment]
@ckdate - May I send in a pull request which updates the repo?

**Comment by ckdake** [comment]
@jasnow of course!

**Comment by jasnow** [comment]
@ckdake - This issue probably is done.
