### ISSUE TITLE
Please push a new version to rubygems

### ISSUE THREAD

**Issue by mcsoup** [ckdake/setler#61]

**Comment by ckdake** [comment]
ETA for this is Saturday Nov 20

**Comment by mcsoup** [comment]
Thank You

**Comment by ckdake** [comment]
Sorry for the delay!  https://github.com/rubygems/rubygems/issues/4761 tripped me up.

**Comment by ckdake** [comment]
https://rubygems.org/gems/setler/versions/0.0.14
